//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceWebAIProject.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmloyeeId { get; set; }
        public string EmployeImageUrl { get; set; }
        public string EmployeeName { get; set; }
        public string EmpolyeeSurname { get; set; }
        public string EmployeeJob { get; set; }
        public string EmployeeSocialMedia1 { get; set; }
        public string EmployeeSocialMedia2 { get; set; }
        public string EmployeeSocialMedia3 { get; set; }
        public string EmployeeSocialMedia4 { get; set; }
    }
}
