//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceWebAIProject.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int FeatureId { get; set; }
        public string FeatureCardIcon { get; set; }
        public string FeatureCardTitle { get; set; }
        public string FeatureCardDescription { get; set; }
    }
}
